In [11]:
import torch
x = torch.arange(4, dtype=torch.float32)
y = torch.ones(4, dtype=torch.float32)
x, y, torch.dot(x, y), sum(x*y)


(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.), tensor(6.))

In [12]:
a = torch.arange(12).reshape(3, 4)
b = torch.arange(4)
a, b, a*b, torch.mv(a, b)


(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([0, 1, 2, 3]),
 tensor([[ 0,  1,  4,  9],
         [ 0,  5, 12, 21],
         [ 0,  9, 20, 33]]),
 tensor([14, 38, 62]))

In [13]:
x = torch.arange(12,dtype=torch.float32).reshape(3,4)
y = torch.arange(12,dtype=torch.float32).reshape(4,3)
torch.mm(x,y)

tensor([[ 42.,  48.,  54.],
        [114., 136., 158.],
        [186., 224., 262.]])

In [21]:

# L2 范数是向量元素平方和的平方根
print(torch.norm(torch.arange(12,dtype=torch.float32)))
# L1 范数表示向量元素的绝对值之和
print(torch.abs(torch.arange(12,dtype=torch.float32)).sum())
# 矩阵的费罗贝尼乌斯范数是矩阵元素的平方和的平方根
print("费罗贝尼乌斯范数：",torch.abs(torch.arange(12,dtype=torch.float32).reshape(3,4)).sum())

tensor(22.4944)
tensor(66.)
费罗贝尼乌斯范数： tensor(66.)
